import express from "express";
import { UserRoutes } from "../modules/user/user.route";
import { TermsRoutes } from "../modules/Terms/Terms.route";
import { AboutRoutes } from "../modules/About/About.route";
import { PrivacyRoutes } from "../modules/privacy/Privacy.route";
import { NotificationRoutes } from "../modules/notifications/notification.route";
import { feedBackRoutes } from "../modules/Feedback/feedback.route";
import { paymentRoutes } from "../modules/payment/payment.route";
import { ServiceRoutes } from "../modules/Service/service.route";
import { MechanicRoutes } from "../modules/Mechanic/mechanic.route";
import { VehicleRoutes } from "../modules/Vehicle/vehicle.route";
import { FavouriteRoutes } from "../modules/Favourite/favourite.route";
import { ChatRoutes } from "../modules/Chat/chat.route";
import { OrderRoutes } from "../modules/Order/order.route";
import { AdminRoutes } from "../modules/Admin/admin.route";
import { commissionRoutes } from "../modules/Commission/commission.route";
import { walletRoutes } from "../modules/Wallet/wallet.route";
import { withdrawRoutes } from "../modules/Withdraw/withdraw.route";
import { PaymentMethodRoutes } from "../modules/PaymentMethod/paymentMethod.route";
import { reviewRoutes } from "../modules/Review/review.route";
import { MechanicServiceRateRoute } from "../modules/MechanicServiceRate/mechanicServiceRate.route";
import { locationTrackingRoutes } from "../modules/locationTracking/locationTracking.route";

const router = express.Router();

router.use("/api/v1/user", UserRoutes);
router.use("/api/v1/chat", ChatRoutes);
router.use("/api/v1/mechanicServiceRate", MechanicServiceRateRoute);
router.use("/api/v1/service", ServiceRoutes);
router.use("/api/v1/admin", AdminRoutes);
router.use("/api/v1/mechanic", MechanicRoutes);
router.use("/api/v1/vehicle", VehicleRoutes);
router.use("/api/v1/review", reviewRoutes);
router.use("/api/v1/order", OrderRoutes);
router.use("/api/v1/commission", commissionRoutes);
router.use("/api/v1/wallet", walletRoutes);
router.use("/api/v1/withdraw", withdrawRoutes);
router.use("/api/v1/payment-method", PaymentMethodRoutes);
router.use("/api/v1/favourite", FavouriteRoutes);
router.use("/api/v1/terms", TermsRoutes);
router.use("/api/v1/about", AboutRoutes);
router.use("/api/v1/privacy", PrivacyRoutes);
router.use("/api/v1/notification", NotificationRoutes);
router.use("/api/v1/feedback", feedBackRoutes);
router.use("/api/v1/purchase", paymentRoutes);
router.use("/api/v1/locationTracking", locationTrackingRoutes);

export default router;
