import express from 'express';
import { createService, getAllServices, getServiceById,updateService,deleteService } from './service.controller';
import { adminMiddleware } from '../../middlewares/auth';
const router = express.Router();
router.post('/create',adminMiddleware("admin"), createService);
router.get('/all', adminMiddleware("admin","user","mechanic"),  getAllServices);
router.get('/:id', adminMiddleware("admin","user","mechanic"), getServiceById);
router.post('/:id', adminMiddleware("admin"), updateService);
router.delete('/:id', adminMiddleware("admin"),deleteService);
export const ServiceRoutes = router;