import express from 'express';
import { createService, getAllServices, getServiceById,updateService,deleteService, deleteServiceByMechanic, addServiceToMechanic } from './service.controller';
import { adminMiddleware } from '../../middlewares/auth';
import upload from '../../middlewares/fileUploadNormal';
const router = express.Router();
router.post('/create',adminMiddleware("admin"), upload.fields([ { name: "image", maxCount: 1 }]), createService);
router.post('/mechanic/add', adminMiddleware("mechanic"),addServiceToMechanic);
router.get('/all', adminMiddleware("admin","user","mechanic"),  getAllServices);
router.get('/:id', adminMiddleware("admin","user","mechanic"), getServiceById);
router.post('/:id', adminMiddleware("admin"), upload.fields([ { name: "image", maxCount: 1 }]), updateService);
router.post('/mechanic/:serviceId', adminMiddleware("mechanic"),deleteServiceByMechanic);
router.delete('/:id', adminMiddleware("admin"),deleteService);
export const ServiceRoutes = router;